import { PrismaClient, TipoTransaccion, EstadoEquipo } from '@prisma/client';

const prisma = new PrismaClient();

const PRODUCTOS_BREMAS = [
  // --- M-0-A ---
  {
    codigoInterno: '4001567',
    modelo: 'CR0120005RT4A',
    nombre: 'Conmutador Manual-0-Automático (M-0-A) 1P 12A',
    marca: 'Bremas',
    precio: 109.24,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de leva de 3 posiciones Manual - 0 - Automático (M-0-A). 1 Polo (1P), corriente nominal 12A. Montaje trascuadro con placa frontal y mando ergonómico.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4001568',
    modelo: 'CR0120006RT4A',
    nombre: 'Conmutador Manual-0-Automático (M-0-A) 2P 12A',
    marca: 'Bremas',
    precio: 141.47,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de leva de 3 posiciones Manual - 0 - Automático (M-0-A). 2 Polos (2P), corriente nominal 12A. Ideal para control y selección de modo en tableros de control.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100071',
    modelo: 'CA0120007W20',
    nombre: 'Conmutador Manual-0-Automático (M-0-A) 3P 12A (Serie CA)',
    marca: 'Bremas',
    precio: 163.03,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador rotativo de leva M-0-A trifásico de 3 Polos (3P), corriente 12A serie CA. Contactos de alta durabilidad eléctrica para automatismos industriales.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4001569',
    modelo: 'CR0120007RT4A',
    nombre: 'Conmutador Manual-0-Automático (M-0-A) 3P 12A (Serie CR)',
    marca: 'Bremas',
    precio: 171.60,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador rotativo de leva M-0-A trifásico de 3 Polos (3P), corriente 12A serie CR con mando rotativo RT4A. Protección y confiabilidad en maniobras de mando.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- 1-0-2 1P ---
  {
    codigoInterno: '4001562',
    modelo: 'CR0120005RT4',
    nombre: 'Conmutador 1-0-2 1P 12A',
    marca: 'Bremas',
    precio: 108.99,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de 3 posiciones I - 0 - II bipolar/unipolar 1 Polo (1P), capacidad 12A. Conmutación segura entre dos circuitos independientes con posición de cero central.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4020945',
    modelo: 'CR0160005RT4',
    nombre: 'Conmutador 1-0-2 1P 16A',
    marca: 'Bremas',
    precio: 115.94,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva de 3 posiciones I - 0 - II de 1 Polo (1P), capacidad 16A. Contactos autolimpiantes de aleación de plata para máxima conductividad.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100031',
    modelo: 'CA0250005PL2',
    nombre: 'Conmutador 1-0-2 1P 25A',
    marca: 'Bremas',
    precio: 167.78,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de potencia I - 0 - II de 1 Polo (1P), capacidad nominal 25A serie CA. Placa frontal grabada 1-0-2 y maneta ergonómica.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- 1-0-2 2P ---
  {
    codigoInterno: '4021462',
    modelo: 'CR0120006RT4',
    nombre: 'Conmutador 1-0-2 2P 12A',
    marca: 'Bremas',
    precio: 136.82,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva I - 0 - II de 2 Polos (2P), capacidad 12A serie CR. Ideal para transferencia manual monofásica de fases o mando.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4022014',
    modelo: 'CR0160006RT6',
    nombre: 'Conmutador 1-0-2 2P 16A',
    marca: 'Bremas',
    precio: 150.35,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva I - 0 - II de 2 Polos (2P), capacidad 16A con mando RT6. Alta robustez para maniobra bajo carga.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021463',
    modelo: 'CR0250006RT6',
    nombre: 'Conmutador 1-0-2 2P 25A',
    marca: 'Bremas',
    precio: 231.92,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de potencia I - 0 - II de 2 Polos (2P), capacidad 25A serie CR. Maniobra confiable para tableros residenciales e industriales.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100041',
    modelo: 'CA0400006PL2',
    nombre: 'Conmutador 1-0-2 2P 40A (Serie CA)',
    marca: 'Bremas',
    precio: 447.60,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de potencia I - 0 - II de 2 Polos (2P), capacidad 40A serie CA con placa PL2. Apto para transferencia monofásica de alta corriente.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4001571',
    modelo: 'CR0400006RT6',
    nombre: 'Conmutador 1-0-2 2P 40A (Serie CR)',
    marca: 'Bremas',
    precio: 471.15,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de potencia I - 0 - II de 2 Polos (2P), capacidad 40A serie CR con mando RT6.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100048',
    modelo: 'CA0500006PL3',
    nombre: 'Conmutador 1-0-2 2P 50A',
    marca: 'Bremas',
    precio: 745.68,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva de potencia I - 0 - II de 2 Polos (2P), capacidad 50A serie CA con placa PL3.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100055',
    modelo: 'CA0630006PL3',
    nombre: 'Conmutador 1-0-2 2P 63A',
    marca: 'Bremas',
    precio: 795.28,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva de potencia I - 0 - II de 2 Polos (2P), capacidad 63A serie CA. Alta capacidad de corte en corriente alterna.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100062',
    modelo: 'CA1000006PL4',
    nombre: 'Conmutador 1-0-2 2P 100A',
    marca: 'Bremas',
    precio: 1736.88,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de gran potencia I - 0 - II de 2 Polos (2P), capacidad 100A serie CA con placa PL4. Diseñado para servicio pesado industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- 1-0-2 3P (TRIFÁSICOS) ---
  {
    codigoInterno: '4100009',
    modelo: 'CA0120007PL1',
    nombre: 'Conmutador 1-0-2 3P 12A',
    marca: 'Bremas',
    precio: 149.79,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de 3 Polos (3P) I - 0 - II, corriente 12A serie CA. Transferencia manual para motores y cargas trifásicas.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021464',
    modelo: 'CR0160007RT6',
    nombre: 'Conmutador 1-0-2 3P 16A',
    marca: 'Bremas',
    precio: 187.83,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de 3 Polos (3P) I - 0 - II, capacidad 16A serie CR con mando rotativo RT6.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021080',
    modelo: 'CR0250007RT6',
    nombre: 'Conmutador 1-0-2 3P 25A',
    marca: 'Bremas',
    precio: 303.78,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de potencia 3 Polos (3P) I - 0 - II, capacidad 25A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021076',
    modelo: 'CR0320007RT6',
    nombre: 'Conmutador 1-0-2 3P 32A',
    marca: 'Bremas',
    precio: 381.48,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de potencia 3 Polos (3P) I - 0 - II, capacidad 32A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021612',
    modelo: 'CR0400007RT6',
    nombre: 'Conmutador 1-0-2 3P 40A',
    marca: 'Bremas',
    precio: 616.87,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de potencia 3 Polos (3P) I - 0 - II, capacidad 40A serie CR para transferencia de red / grupo.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100049',
    modelo: 'CA0500007PL3',
    nombre: 'Conmutador 1-0-2 3P 50A',
    marca: 'Bremas',
    precio: 927.26,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de potencia 3 Polos (3P) I - 0 - II, capacidad 50A serie CA con placa PL3.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100056',
    modelo: 'CA0630007PL3',
    nombre: 'Conmutador 1-0-2 3P 63A',
    marca: 'Bremas',
    precio: 1066.34,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de potencia 3 Polos (3P) I - 0 - II, capacidad 63A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100063',
    modelo: 'CA1000007PL4',
    nombre: 'Conmutador 1-0-2 3P 100A',
    marca: 'Bremas',
    precio: 2332.28,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de alta potencia trifásico de 3 Polos (3P) I - 0 - II, capacidad 100A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- 1-0-2 4P (TETRAPOLARES) ---
  {
    codigoInterno: '4100072',
    modelo: 'CA0120039PL1',
    nombre: 'Conmutador 1-0-2 4P 12A (3P + Neutro)',
    marca: 'Bremas',
    precio: 235.18,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador tetrapolar de 4 Polos (4P) I - 0 - II, capacidad 12A serie CA. Conmuta las 3 fases y el neutro simultáneamente.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100076',
    modelo: 'CA0250039PL2',
    nombre: 'Conmutador 1-0-2 4P 25A (3P + Neutro)',
    marca: 'Bremas',
    precio: 457.54,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador tetrapolar de 4 Polos (4P) I - 0 - II, capacidad 25A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100078',
    modelo: 'CA0500039PL3',
    nombre: 'Conmutador 1-0-2 4P 50A (3P + Neutro)',
    marca: 'Bremas',
    precio: 1085.57,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador tetrapolar de potencia 4 Polos (4P) I - 0 - II, capacidad 50A serie CA con corte de neutro.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100080',
    modelo: 'CA0630039PL3',
    nombre: 'Conmutador 1-0-2 4P 63A (3P + Neutro)',
    marca: 'Bremas',
    precio: 1342.29,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador tetrapolar de potencia 4 Polos (4P) I - 0 - II, capacidad 63A serie CA con corte de neutro.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- CON RETORNO ---
  {
    codigoInterno: '4100067',
    modelo: 'CS0120077PL1',
    nombre: 'Conmutador 1-0-2 con Retorno Automático 1P 12A',
    marca: 'Bremas',
    precio: 101.35,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador con mecanismo de retorno por resorte automático a la posición central 0. 1 Polo (1P), 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100070',
    modelo: 'CA0120481PL1V',
    nombre: 'Conmutador 1-0-2 con Retorno Automático 3P 12A',
    marca: 'Bremas',
    precio: 163.04,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador trifásico de 3 Polos (3P) con retorno por resorte a cero, corriente 12A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- DOBLE VELOCIDAD 1-0-2 ---
  {
    codigoInterno: '4021465',
    modelo: 'CR0120009RT4',
    nombre: 'Conmutador Doble Velocidad 1-0-2 3P 12A',
    marca: 'Bremas',
    precio: 201.77,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de leva para motores de dos velocidades (Dahlander / Devanados independientes). 3 Polos, 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4020946',
    modelo: 'CR0160009RT4',
    nombre: 'Conmutador Doble Velocidad 1-0-2 3P 16A',
    marca: 'Bremas',
    precio: 229.56,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador para control de motores de dos velocidades. 3 Polos, 16A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021466',
    modelo: 'CR0250009RT6',
    nombre: 'Conmutador Doble Velocidad 1-0-2 3P 25A',
    marca: 'Bremas',
    precio: 380.33,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador para motores Dahlander de dos velocidades 3 Polos, capacidad 25A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4021077',
    modelo: 'CR0400009RT6',
    nombre: 'Conmutador Doble Velocidad 1-0-2 3P 40A',
    marca: 'Bremas',
    precio: 732.84,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de potencia para motores Dahlander de 2 velocidades. 3 Polos, 40A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100051',
    modelo: 'CA0500009PL3',
    nombre: 'Conmutador Doble Velocidad 1-0-2 3P 50A',
    marca: 'Bremas',
    precio: 1098.74,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de alta potencia para motores de dos velocidades. 3 Polos, 50A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100058',
    modelo: 'CA0630009PL3',
    nombre: 'Conmutador Doble Velocidad 1-0-2 3P 63A',
    marca: 'Bremas',
    precio: 1405.74,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de alta potencia para motores de dos velocidades. 3 Polos, 63A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- DOBLE VELOCIDAD 0-1-2 ---
  {
    codigoInterno: '4100073',
    modelo: 'CS0127837W21',
    nombre: 'Conmutador Doble Velocidad 0-1-2 3P 12A',
    marca: 'Bremas',
    precio: 200.48,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva para selección de velocidad progresiva 0 - 1 - 2. 3 Polos, 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100077',
    modelo: 'CS0257837PL2',
    nombre: 'Conmutador Doble Velocidad 0-1-2 3P 25A',
    marca: 'Bremas',
    precio: 361.32,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva 0 - 1 - 2 de 3 Polos, capacidad 25A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100079',
    modelo: 'CS0407837PL3',
    nombre: 'Conmutador Doble Velocidad 0-1-2 3P 50A',
    marca: 'Bremas',
    precio: 663.11,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva 0 - 1 - 2 de 3 Polos, capacidad 50A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4104660',
    modelo: 'CS0637837PL3',
    nombre: 'Conmutador Doble Velocidad 0-1-2 3P 63A',
    marca: 'Bremas',
    precio: 883.43,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Conmutador de leva 0 - 1 - 2 de 3 Polos, capacidad 63A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- VELOCIDAD CON INVERSIÓN ---
  {
    codigoInterno: '4100013',
    modelo: 'CA0120011PL1',
    nombre: 'Conmutador de Velocidad con Inversión (2-0-1-0-1-0-2) 3P 12A',
    marca: 'Bremas',
    precio: 293.02,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo especial para selección de 2 velocidades en ambos sentidos de giro (Inversor + 2 velocidades). 3 Polos, 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100037',
    modelo: 'CA0250011PL2',
    nombre: 'Conmutador de Velocidad con Inversión (2-0-1-0-1-0-2) 3P 25A',
    marca: 'Bremas',
    precio: 478.06,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo especial para selección de 2 velocidades e inversión de giro. 3 Polos, 25A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- ESTRELLA TRIÁNGULO ---
  {
    codigoInterno: '4100027',
    modelo: 'CA0160010PL2',
    nombre: 'Arrancador Manual Estrella - Triángulo (Y-Δ) 16A',
    marca: 'Bremas',
    precio: 215.90,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de leva para arranque manual de motores trifásicos en Estrella-Triángulo (0 - Y - Δ). Capacidad 16A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100036',
    modelo: 'CA0250010PL2',
    nombre: 'Arrancador Manual Estrella - Triángulo (Y-Δ) 25A',
    marca: 'Bremas',
    precio: 356.90,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de leva para arranque Estrella-Triángulo manual (0 - Y - Δ). Capacidad 25A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100045',
    modelo: 'CA0400010PL2',
    nombre: 'Arrancador Manual Estrella - Triángulo (Y-Δ) 40A',
    marca: 'Bremas',
    precio: 696.21,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de leva para arranque Estrella-Triángulo manual (0 - Y - Δ). Capacidad 40A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100052',
    modelo: 'CA0500010PL3',
    nombre: 'Arrancador Manual Estrella - Triángulo (Y-Δ) 50A',
    marca: 'Bremas',
    precio: 1173.50,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de potencia para arranque Estrella-Triángulo (0 - Y - Δ). Capacidad 50A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100059',
    modelo: 'CA0630010PL3',
    nombre: 'Arrancador Manual Estrella - Triángulo (Y-Δ) 63A',
    marca: 'Bremas',
    precio: 1486.84,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de potencia para arranque Estrella-Triángulo (0 - Y - Δ). Capacidad 63A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- VOLTIMÉTRICOS ---
  {
    codigoInterno: '4020941',
    modelo: 'CR0120016RT4',
    nombre: 'Conmutador Voltimétrico 3 Fases (0 - L1L2 - L2L3 - L3L1)',
    marca: 'Bremas',
    precio: 132.18,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector voltimétrico para medición de 3 tensiones entre fases (L-L) con un solo voltímetro. 4 Posiciones: 0, L1-L2, L2-L3, L3-L1. Corriente 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100016',
    modelo: 'CA0120018PL1',
    nombre: 'Conmutador Voltimétrico 3 Fases + Neutro (7 Posiciones) Serie CA',
    marca: 'Bremas',
    precio: 160.80,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector voltimétrico de 7 posiciones para lectura de 3 tensiones de fase (L-N) y 3 tensiones compuestas (L-L): L3L1 - L2L3 - L1L2 - 0 - L1N - L2N - L3N. 12A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4001565',
    modelo: 'CR0120018RT4',
    nombre: 'Conmutador Voltimétrico 3 Fases + Neutro (7 Posiciones) Serie CR',
    marca: 'Bremas',
    precio: 169.26,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector voltimétrico de 7 posiciones para lectura de 3 tensiones de fase (L-N) y 3 compuestas (L-L): L3L1 - L2L3 - L1L2 - 0 - L1N - L2N - L3N. 12A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- AMPERIMÉTRICOS ---
  {
    codigoInterno: '4020942',
    modelo: 'CR0120022RT4',
    nombre: 'Conmutador Amperimétrico 3 Transformadores (0-1-2-3) 1P 12A',
    marca: 'Bremas',
    precio: 169.26,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector amperimétrico para 3 transformadores de corriente (TC / CT) con 1 amperímetro. Conexión segura con cortocircuito automático de secundarios sin abrir. 1P, 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100018',
    modelo: 'CA0120025PL1',
    nombre: 'Conmutador Amperimétrico 3 Transformadores (0-1-2-3) 2P 12A',
    marca: 'Bremas',
    precio: 322.00,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector amperimétrico bipolar para 3 transformadores de corriente (TC). 4 posiciones: 0 - 1 - 2 - 3. 2P, 12A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4100075',
    modelo: 'CS0127839W21',
    nombre: 'Conmutador Amperimétrico 0-R-S-T 12A',
    marca: 'Bremas',
    precio: 123.38,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector amperimétrico rotativo para lectura de corriente por fase en líneas R-S-T. 12A.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
  {
    codigoInterno: '4104657',
    modelo: 'CA0250014PL2',
    nombre: 'Conmutador Amperimétrico 0-R-0-S-0-T 25A',
    marca: 'Bremas',
    precio: 422.98,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores Voltimétricos y Amperimétricos',
    descripcion: 'Selector amperimétrico con posición de cero intermedia entre fases (0-R-0-S-0-T). 25A serie CA.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },

  // --- CONMUTADOR DE BOMBAS ---
  {
    codigoInterno: '4021078',
    modelo: 'CR0127838W21',
    nombre: 'Conmutador de Bombas con Alternancia (0 - B1 - B2 - ALT) 12A',
    marca: 'Bremas',
    precio: 147.15,
    categoria: 'Conmutadores',
    subfamiliaNombre: 'Conmutadores y Selectores',
    descripcion: 'Interruptor rotativo de 4 posiciones diseñado para control de electrobombas y sistemas hidroneumáticos: Parada (0), Bomba 1 (B1), Bomba 2 (B2) y Modo Alternado automático (ALT). 12A serie CR.',
    imagenUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800',
  },
];

async function main() {
  console.log('🚀 Iniciando importación de 54 conmutadores Bremas para Venta...');

  // 1. Obtener o crear la Familia "Equipos Especiales"
  let familia = await prisma.familia.findUnique({
    where: { nombre: 'Equipos Especiales' },
  });

  if (!familia) {
    familia = await prisma.familia.create({
      data: {
        nombre: 'Equipos Especiales',
        descripcion: 'Equipos especializados: conmutadores de leva, climatización, subestaciones, transformadores, celdas de MT.',
      },
    });
  }

  // 2. Subfamilias necesarias
  const subfamiliasNombres = [
    'Conmutadores y Selectores',
    'Conmutadores Voltimétricos y Amperimétricos',
  ];

  const subfamiliasMap = new Map<string, string>();

  for (const nombre of subfamiliasNombres) {
    let subfamilia = await prisma.subfamilia.findUnique({
      where: {
        familiaId_nombre: {
          familiaId: familia.id,
          nombre,
        },
      },
    });

    if (!subfamilia) {
      subfamilia = await prisma.subfamilia.create({
        data: {
          nombre,
          familiaId: familia.id,
        },
      });
    }

    subfamiliasMap.set(nombre, subfamilia.id);
  }

  // 3. Upsert de cada conmutador Bremas
  let creados = 0;
  for (const prod of PRODUCTOS_BREMAS) {
    const subfamiliaId = subfamiliasMap.get(prod.subfamiliaNombre);

    await prisma.equipo.upsert({
      where: { codigoInterno: prod.codigoInterno },
      update: {
        nombre: prod.nombre,
        modelo: prod.modelo,
        marca: prod.marca,
        precio: prod.precio,
        tipo: TipoTransaccion.VENTA,
        estado: EstadoEquipo.DISPONIBLE,
        disponible: true,
        categoria: prod.categoria,
        descripcion: prod.descripcion,
        imagenUrl: prod.imagenUrl,
        unidad: 'Unidad',
        ubicacion: 'Almacén Central',
        familiaId: familia.id,
        subfamiliaId: subfamiliaId,
      },
      create: {
        codigoInterno: prod.codigoInterno,
        nombre: prod.nombre,
        modelo: prod.modelo,
        marca: prod.marca,
        precio: prod.precio,
        tipo: TipoTransaccion.VENTA,
        estado: EstadoEquipo.DISPONIBLE,
        disponible: true,
        categoria: prod.categoria,
        descripcion: prod.descripcion,
        imagenUrl: prod.imagenUrl,
        unidad: 'Unidad',
        ubicacion: 'Almacén Central',
        familiaId: familia.id,
        subfamiliaId: subfamiliaId,
      },
    });

    console.log(`  ✅ [${prod.codigoInterno}] ${prod.nombre} - S/ ${prod.precio}`);
    creados++;
  }

  console.log(`\n🎉 Total de conmutadores Bremas importados con éxito: ${creados}`);
}

main()
  .catch((e) => {
    console.error('❌ Error en importación Bremas:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
