import { PrismaClient, TipoTransaccion, EstadoEquipo } from '@prisma/client';

const prisma = new PrismaClient();

// ==========================================
// 1. DEHN SEÑAL Y CAMPO (15 ÍTEMS - USD)
// ==========================================
const DEHN_SENAL = [
  {
    codigoInterno: '4017851',
    modelo: '920300',
    nombre: 'Base para Módulo DPS de Señal sin Desconexión BXT BAS (BLITZDUCTOR XT)',
    marca: 'Dehn',
    precio: 77.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo base pasivo universal de 4 polos para módulos de protección enchufables BLITZDUCTOR XT. Permite cambio de módulo sin interrupción de señal (LifeCheck integrado). Montaje en Riel DIN 35mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4018809',
    modelo: '920271',
    nombre: 'Cartucho DPS Señal Tipo 1+2 para Redes Profibus DP 2 Hilos (BXT ML2 BD HF 5)',
    marca: 'Dehn',
    precio: 280.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable de protección combinada contra rayos y sobretensiones Tipo 1 + Tipo 2 (D1/C2) para buses de campo de alta frecuencia Profibus DP y RS485. 2 hilos / 1 par.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4018654',
    modelo: '920222',
    nombre: 'Cartucho DPS Señal Tipo 1+2 2 Hilos Un=12V (BXT ML2 BE 12)',
    marca: 'Dehn',
    precio: 268.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable de protección combinada Tipo 1 + Tipo 2 para 2 señales analógicas o digitales con potencial de referencia común (BE). Tensión nominal Un=12V DC.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4018898',
    modelo: '920244',
    nombre: 'Cartucho DPS Señal Tipo 1+2 2 Hilos Un=24V Analógico (BXT ML2 BD 24)',
    marca: 'Dehn',
    precio: 250.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo de protección Tipo 1 + Tipo 2 para 1 par aislado galvánicamente (bucle de corriente 4-20mA, señales analógicas de 24V). Tensión nominal Un=24V DC.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4017852',
    modelo: '920224',
    nombre: 'Cartucho DPS Señal Tipo 1+2 2 Hilos Un=24V Digital (BXT ML2 BE 24)',
    marca: 'Dehn',
    precio: 264.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable Tipo 1 + Tipo 2 para 2 señales digitales con masa común (señales binarias 24V DC de control y PLC).',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4022072',
    modelo: '920320',
    nombre: 'Cartucho DPS Señal Tipo 1+2 4 Hilos Un=5V (BXT ML4 BE 5)',
    marca: 'Dehn',
    precio: 405.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo de protección combinada Tipo 1 + Tipo 2 para 4 señales de bajo voltaje TTL/CMOS de 5V DC con potencial de referencia común.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4017848',
    modelo: '920344',
    nombre: 'Cartucho DPS Señal Tipo 1+2 4 Hilos Un=24V Analógico (BXT ML4 BD 24)',
    marca: 'Dehn',
    precio: 376.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable Tipo 1 + Tipo 2 para 2 pares aislados galvánicamente (hasta 2 canales analógicos de 4-20mA / 0-10V en un solo módulo). Tensión nominal Un=24V DC.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4019598',
    modelo: '920324',
    nombre: 'Cartucho DPS Señal Tipo 1+2 4 Hilos Un=24V Digital (BXT ML4 BE 24)',
    marca: 'Dehn',
    precio: 397.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable Tipo 1 + Tipo 2 para 4 señales digitales de 24V con masa común (alta densidad de puntos de I/O de PLC en 1 módulo DIN).',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4017849',
    modelo: '920327',
    nombre: 'Cartucho DPS Señal Tipo 1+2 4 Hilos Un=180V (BXT ML4 BE 180)',
    marca: 'Dehn',
    precio: 405.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable Tipo 1 + Tipo 2 para 4 señales de alta impedancia o líneas de telecomunicaciones y control de hasta 180V.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4018897',
    modelo: '920389',
    nombre: 'Cartucho DPS Señal Tipo 1+2 4 Hilos Un=250V (BXT ML4 BD 250)',
    marca: 'Dehn',
    precio: 405.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Módulo enchufable Tipo 1 + Tipo 2 para 2 pares diferenciales en circuitos de control y señalización de hasta 250V AC/DC.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4019883',
    modelo: '929941',
    nombre: 'Supresor DPS de Campo para Transmisor 2 Hilos Un=24V Rosca M20 (DEHNpipe)',
    marca: 'Dehn',
    precio: 319.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Descargador de sobretensiones en carcasa de acero inoxidable para montaje directo roscado (M20x1.5) en cabezales de transmisores de presión, flujo o temperatura de 2 hilos (4-20mA). Grado IP67.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4019732',
    modelo: '929970',
    nombre: 'Supresor DPS de Campo 4+1 Hilos Un=24V 120/250V Rosca NPT (DEHNpipe)',
    marca: 'Dehn',
    precio: 536.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Descargador de campo para instrumentación multihilo con rosca 1/2" NPT. Protección combinada de alimentación (120/250V) y señales de 24V en envolvente robusta de acero inoxidable.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4020656',
    modelo: '929951',
    nombre: 'Supresor DPS de Campo 4+1 Hilos Un=24V / 24V Rosca NPT (DEHNpipe)',
    marca: 'Dehn',
    precio: 377.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Descargador de campo para sensores e instrumentos de 4 hilos (alimentación 24V + señal 24V) con conexión 1/2" NPT y protección IP67.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4017740',
    modelo: '929121',
    nombre: 'Supresor DPS Señal Ethernet RJ45 Cat 6 / Clase E PoE+ (DEHNpatch)',
    marca: 'Dehn',
    precio: 274.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Dispositivo de protección contra sobretensiones para redes de datos Gigabit Ethernet (1000Base-T), Cat 6 / Clase E y alimentación sobre Ethernet Power-over-Ethernet (PoE / PoE+). Conectores hembra RJ45 apantallados.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4019884',
    modelo: '924017',
    nombre: 'Supresor DPS Señal Sub-D 9 Pines Profibus DP (DEHNconnect)',
    marca: 'Dehn',
    precio: 367.00,
    unidad: 'USD',
    categoria: 'Supresores de Señal y Datos',
    subfamilia: 'Supresores de Sobretensión (DPS)',
    familia: 'Equipos Especiales',
    descripcion: 'Adaptador de protección contra sobretensiones con conector Sub-D de 9 polos macho/hembra para interfaces de comunicación Profibus DP, RS485 o Modbus RTU en PLCs y paneles de control.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
];

// ==========================================
// 2. E-SAFE TABLEROS Y CAJAS PVC (29 ÍTEMS - PEN)
// ==========================================
const ESAFE_TABLEROS_CAJAS = [
  {
    codigoInterno: '4101743',
    modelo: 'HG II 2P METAL',
    nombre: 'Caja para Adosar 2 Polos sin Tapa HG II 2P Metal',
    marca: 'E-safe Tableros PVC',
    precio: 6.21,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja adosable termoplástica para 2 módulos en riel DIN, con soporte metálico para fijación sin tapa frontal.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101744',
    modelo: 'HG II 4P METAL',
    nombre: 'Caja para Adosar 4 Polos sin Tapa HG II 4P Metal',
    marca: 'E-safe Tableros PVC',
    precio: 6.21,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja adosable termoplástica para 4 módulos en riel DIN sin tapa.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005021',
    modelo: 'BSM 2W',
    nombre: 'Caja para Adosar 2 Polos con Tapa Fumé BSM 2W',
    marca: 'E-safe Tableros PVC',
    precio: 7.82,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de distribución adosable para 2 polos con puerta transparente abatible en policarbonato.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4008574',
    modelo: 'BSM 4W',
    nombre: 'Caja para Adosar 4 Polos con Tapa Fumé BSM 4W',
    marca: 'E-safe Tableros PVC',
    precio: 13.62,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de distribución adosable para 4 polos con riel DIN y puerta transparente.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005020',
    modelo: 'BSM 8W',
    nombre: 'Caja para Adosar 8 Polos con Tapa Fumé BSM 8W',
    marca: 'E-safe Tableros PVC',
    precio: 20.22,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de distribución adosable para 8 polos con puerta abatible termoplástica.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4008575',
    modelo: 'BSM 12W',
    nombre: 'Caja para Adosar 12 Polos con Tapa Fumé BSM 12W',
    marca: 'E-safe Tableros PVC',
    precio: 26.10,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de distribución adosable para 12 polos riel DIN con tapa fumé abatible.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101745',
    modelo: 'D6-HPK 2W',
    nombre: 'Tablero para Empotrar 2 Polos D6-HPK 2W',
    marca: 'E-safe Tableros PVC',
    precio: 7.82,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero termoplástico para empotrar de 2 polos con tapa y riel DIN.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101746',
    modelo: 'D6-HPK 4W',
    nombre: 'Tablero para Empotrar 4 Polos D6-HPK 4W',
    marca: 'E-safe Tableros PVC',
    precio: 13.62,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero termoplástico para empotrar de 4 polos con riel DIN.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101747',
    modelo: 'D6-HPK 6W',
    nombre: 'Tablero para Empotrar 6 Polos D6-HPK 6W',
    marca: 'E-safe Tableros PVC',
    precio: 15.20,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero de distribución para empotrar de 6 polos.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101748',
    modelo: 'D6-HPK 8W',
    nombre: 'Tablero para Empotrar 8 Polos D6-HPK 8W',
    marca: 'E-safe Tableros PVC',
    precio: 20.22,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero de distribución para empotrar de 8 polos.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101749',
    modelo: 'D6-HPK 12W',
    nombre: 'Tablero para Empotrar 12 Polos D6-HPK 12W',
    marca: 'E-safe Tableros PVC',
    precio: 26.10,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero de distribución para empotrar de 12 polos.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101751',
    modelo: 'D6-HPK 18W',
    nombre: 'Tablero para Empotrar 18 Polos D6-HPK 18W',
    marca: 'E-safe Tableros PVC',
    precio: 38.72,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero de distribución para empotrar de 18 polos.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4101752',
    modelo: 'D6-HPK 24W',
    nombre: 'Tablero para Empotrar 24 Polos D6-HPK 24W',
    marca: 'E-safe Tableros PVC',
    precio: 62.10,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero de distribución para empotrar de 24 polos en 2 filas.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104683',
    modelo: 'D6-HPK 36W',
    nombre: 'Tablero para Empotrar 36 Polos D6-HPK 36W',
    marca: 'E-safe Tableros PVC',
    precio: 78.88,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tablero de distribución para empotrar de 36 polos en 3 filas.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104684',
    modelo: '85X85X50 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 85x85x50 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 7.24,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de derivación y paso estanca IP65 con conos pasacables de goma 85x85x50 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104685',
    modelo: '85X85X50 SIN CONOS',
    nombre: 'Caja de Pase sin Conos (Cieguita) 85x85x50 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 7.24,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca paredes lisas sin conos 85x85x50 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104686',
    modelo: '100X100X70 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 100x100x70 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 9.39,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de derivación estanca IP65 con conos pasacables 100x100x70 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104687',
    modelo: '100X100X70 SIN CONOS',
    nombre: 'Caja de Pase sin Conos 100x100x70 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 9.39,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca lisa IP65 100x100x70 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104688',
    modelo: '150X150X70 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 150x150x70 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 12.42,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de derivación estanca IP65 con conos 150x150x70 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104689',
    modelo: '150X150X70 SIN CONOS',
    nombre: 'Caja de Pase sin Conos 150x150x70 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 12.42,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca lisa 150x150x70 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104690',
    modelo: '150X110X70 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 150x110x70 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 11.15,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de derivación estanca rectangular con conos 150x110x70 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104691',
    modelo: '150X110X70 SIN CONOS',
    nombre: 'Caja de Pase sin Conos 150x110x70 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 11.15,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca lisa 150x110x70 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104692',
    modelo: '200X155X80 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 200x155x80 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 20.22,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de derivación estanca con conos 200x155x80 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104693',
    modelo: '200X155X80 SIN CONOS',
    nombre: 'Caja de Pase sin Conos 200x155x80 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 20.22,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca lisa 200x155x80 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104694',
    modelo: '200X200X80 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 200x200x80 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 23.17,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso cuadrada estanca con conos 200x200x80 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104695',
    modelo: '200X200X80 SIN CONOS',
    nombre: 'Caja de Pase sin Conos 200x200x80 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 23.17,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso cuadrada estanca lisa 200x200x80 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104696',
    modelo: '255X200X80 CONOS',
    nombre: 'Caja de Pase con Conos de Goma 255x200x80 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 32.13,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca grande con conos 255x200x80 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4104697',
    modelo: '255X200X80 SIN CONOS',
    nombre: 'Caja de Pase sin Conos 255x200x80 mm IP65',
    marca: 'E-safe Tableros PVC',
    precio: 32.13,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Caja de paso estanca grande lisa 255x200x80 mm.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4020956',
    modelo: 'TAP',
    nombre: 'Tapa Obturadora para Reserva Riel DIN',
    marca: 'E-safe Tableros PVC',
    precio: 1.31,
    unidad: 'PEN',
    categoria: 'Tableros y Cajas PVC',
    subfamilia: 'Cajas y Tableros PVC',
    familia: 'Tableros Eléctricos',
    descripcion: 'Tapa obturadora modular termoplástica para cubrir espacios de reserva libres en tableros con riel DIN.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
];

// ==========================================
// 3. E-SAFE CINTILLOS Y ORGANIZADORES (33 ÍTEMS - PEN)
// ==========================================
const ESAFE_CINTILLOS = [
  {
    codigoInterno: '4006559',
    modelo: 'HS-100A WHITE',
    nombre: 'Cintillo Plástico Blanco 2.5x100 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 3.82,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Amarres plásticos de nylon blanco 2.5 x 100 mm para peinado de cables en tableros. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006561',
    modelo: 'HS-150B WHITE',
    nombre: 'Cintillo Plástico Blanco 3.6x150 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 8.53,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon blanco 3.6 x 150 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006562',
    modelo: 'HS-180B WHITE',
    nombre: 'Cintillo Plástico Blanco 3.6x180 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 13.54,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon blanco 3.6 x 180 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006563',
    modelo: 'HS-200B WHITE',
    nombre: 'Cintillo Plástico Blanco 3.6x200 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 15.16,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon blanco 3.6 x 200 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006564',
    modelo: 'HS-200C WHITE',
    nombre: 'Cintillo Plástico Blanco 4.8x200 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 17.95,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon reforzado blanco 4.8 x 200 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006565',
    modelo: 'HS-250C WHITE',
    nombre: 'Cintillo Plástico Blanco 4.8x250 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 21.20,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon blanco 4.8 x 250 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006566',
    modelo: 'HS-300C WHITE',
    nombre: 'Cintillo Plástico Blanco 4.8x300 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 25.74,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon blanco 4.8 x 300 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006567',
    modelo: 'HS-370C WHITE',
    nombre: 'Cintillo Plástico Blanco 4.8x370 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 38.85,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon blanco 4.8 x 370 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006568',
    modelo: 'HS-530C WHITE',
    nombre: 'Cintillo Plástico Blanco 4.8x530 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 78.58,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos largos de nylon blanco 4.8 x 530 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006569',
    modelo: 'HS-370D WHITE',
    nombre: 'Cintillo Plástico Blanco 7.6x370 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 88.60,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos pesados de nylon blanco 7.6 x 370 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006570',
    modelo: 'HS-400D WHITE',
    nombre: 'Cintillo Plástico Blanco 7.6x400 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 90.21,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos pesados de nylon blanco 7.6 x 400 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006571',
    modelo: 'HS-100A BLACK',
    nombre: 'Cintillo Plástico Negro UV 2.5x100 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 3.82,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro con protección UV 2.5 x 100 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006572',
    modelo: 'HS-150B BLACK',
    nombre: 'Cintillo Plástico Negro UV 3.6x150 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 11.47,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro UV 3.6 x 150 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006573',
    modelo: 'HS-200B BLACK',
    nombre: 'Cintillo Plástico Negro UV 3.6x200 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 16.20,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro UV 3.6 x 200 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006574',
    modelo: 'HS-200C BLACK',
    nombre: 'Cintillo Plástico Negro UV 4.8x200 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 18.09,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon reforzado negro UV 4.8 x 200 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006575',
    modelo: 'HS-250C BLACK',
    nombre: 'Cintillo Plástico Negro UV 4.8x250 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 21.20,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro UV 4.8 x 250 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006576',
    modelo: 'HS-300C BLACK',
    nombre: 'Cintillo Plástico Negro UV 4.8x300 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 27.38,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro UV 4.8 x 300 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006577',
    modelo: 'HS-370C BLACK',
    nombre: 'Cintillo Plástico Negro UV 4.8x370 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 38.85,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro UV 4.8 x 370 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006578',
    modelo: 'HS-400C BLACK',
    nombre: 'Cintillo Plástico Negro UV 4.8x400 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 43.11,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos de nylon negro UV 4.8 x 400 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006579',
    modelo: 'HS-300D BLACK',
    nombre: 'Cintillo Plástico Negro UV 7.6x300 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 95.21,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos pesados de nylon negro UV 7.6 x 300 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006580',
    modelo: 'HS-370D BLACK',
    nombre: 'Cintillo Plástico Negro UV 7.6x370 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 77.99,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos pesados de nylon negro UV 7.6 x 370 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006581',
    modelo: 'HS-550DL BLACK',
    nombre: 'Cintillo Plástico Negro UV Extra Pesado 9.0x550 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 158.62,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos extra pesados de nylon negro UV 9.0 x 550 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006582',
    modelo: 'HS-650DL BLACK',
    nombre: 'Cintillo Plástico Negro UV Extra Pesado 9.0x650 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 180.72,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos extra pesados de nylon negro UV 9.0 x 650 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006583',
    modelo: 'HS-760DL BLACK',
    nombre: 'Cintillo Plástico Negro UV Extra Pesado 9.0x760 mm (Bolsa de 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 299.02,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Cintillos extra pesados de nylon negro UV 9.0 x 760 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006592',
    modelo: 'HSP-20',
    nombre: 'Base Portacintillo Autoadhesiva 20x20 mm (Bolsa x 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 21.34,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Bases adhesivas y atornillables para fijación de cintillos 20x20 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006591',
    modelo: 'HSP-25',
    nombre: 'Base Portacintillo Autoadhesiva 25x25 mm (Bolsa x 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 34.73,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Bases adhesivas para fijación de cintillos 25x25 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006594',
    modelo: 'HSP-30',
    nombre: 'Base Portacintillo Autoadhesiva 30x30 mm (Bolsa x 100 Und)',
    marca: 'E-safe Tableros PVC',
    precio: 53.41,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Bases adhesivas para fijación de cintillos 30x30 mm. Bolsa x 100 unidades.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006584',
    modelo: 'HS-SWB-06',
    nombre: 'Espiral Envolvente Organizador de Cables 6 mm x 10 m',
    marca: 'E-safe Tableros PVC',
    precio: 13.54,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Tubo espiral flexible de polietileno de 6 mm para agrupamiento y protección de conductores eléctricos. Rollo x 10 metros.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006585',
    modelo: 'HS-SWB-08',
    nombre: 'Espiral Envolvente Organizador de Cables 8 mm x 10 m',
    marca: 'E-safe Tableros PVC',
    precio: 13.24,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Tubo espiral flexible de polietileno de 8 mm para conductores eléctricos. Rollo x 10 metros.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006586',
    modelo: 'HS-SWB-10',
    nombre: 'Espiral Envolvente Organizador de Cables 10 mm x 10 m',
    marca: 'E-safe Tableros PVC',
    precio: 18.26,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Tubo espiral flexible de polietileno de 10 mm. Rollo x 10 metros.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006587',
    modelo: 'HS-SWB-12',
    nombre: 'Espiral Envolvente Organizador de Cables 12 mm x 10 m',
    marca: 'E-safe Tableros PVC',
    precio: 22.96,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Tubo espiral flexible de polietileno de 12 mm. Rollo x 10 metros.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006588',
    modelo: 'HS-SWB-15',
    nombre: 'Espiral Envolvente Organizador de Cables 15 mm x 10 m',
    marca: 'E-safe Tableros PVC',
    precio: 36.19,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Tubo espiral flexible de polietileno de 15 mm. Rollo x 10 metros.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
  {
    codigoInterno: '4006589',
    modelo: 'HS-SWB-19',
    nombre: 'Espiral Envolvente Organizador de Cables 19 mm x 10 m',
    marca: 'E-safe Tableros PVC',
    precio: 44.15,
    unidad: 'PEN',
    categoria: 'Cintillos y Accesorios',
    subfamilia: 'Cintillos y Amarres',
    familia: 'Equipos Eléctricos',
    descripcion: 'Tubo espiral flexible de polietileno de 19 mm. Rollo x 10 metros.',
    imagenUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?q=80&w=800',
  },
];

// ==========================================
// 4. EATON INTERRUPTORES DE RIEL (24 ÍTEMS - PEN)
// ==========================================
const EATON_ITM = [
  // --- 1 POLO (14 Ítems) ---
  {
    codigoInterno: '4005732',
    modelo: 'mMC6-C10/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 10A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 9.15,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor automático termomagnético en miniatura (MCB) unipolar 1P de 10A, curva C, capacidad de corte 6kA según IEC/EN 60898-1 / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005733',
    modelo: 'mMC6-C16/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 16A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 11.79,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 16A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005734',
    modelo: 'mMC6-C20/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 20A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 11.32,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 20A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005735',
    modelo: 'mMC6-C25/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 25A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 10.40,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 25A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005736',
    modelo: 'mMC6-C32/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 32A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 14.87,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 32A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005737',
    modelo: 'mMC6-C40/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 40A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 11.92,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 40A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005738',
    modelo: 'mMC6-C50/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 50A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 24.70,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 50A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005739',
    modelo: 'mMC6-C63/1',
    nombre: 'Interruptor Termomagnético Riel DIN 1P 63A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 35.89,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 63A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004118',
    modelo: 'mMCM-C20/1',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 1P 20A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 11.79,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor automático termomagnético de alto rendimiento 1P 20A, capacidad de corte 10kA / 400V para uso industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004119',
    modelo: 'mMCM-C25/1',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 1P 25A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 14.57,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 25A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004120',
    modelo: 'mMCM-C32/1',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 1P 32A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 41.47,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 32A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004121',
    modelo: 'mMCM-C40/1',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 1P 40A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 16.52,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 40A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004122',
    modelo: 'mMCM-C50/1',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 1P 50A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 24.68,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 50A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004123',
    modelo: 'mMCM-C63/1',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 1P 63A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 38.25,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 1P 63A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },

  // --- 2 POLOS (10 Ítems) ---
  {
    codigoInterno: '4005740',
    modelo: 'mMC6-C10/2',
    nombre: 'Interruptor Termomagnético Riel DIN 2P 10A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 25.57,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor automático termomagnético bipolar 2P 10A, curva C, capacidad de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005744',
    modelo: 'mMC6-C32/2',
    nombre: 'Interruptor Termomagnético Riel DIN 2P 32A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 20.91,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 2P 32A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005745',
    modelo: 'mMC6-C40/2',
    nombre: 'Interruptor Termomagnético Riel DIN 2P 40A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 26.85,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 2P 40A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005746',
    modelo: 'mMC6-C50/2',
    nombre: 'Interruptor Termomagnético Riel DIN 2P 50A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 47.85,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 2P 50A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005747',
    modelo: 'mMC6-C63/2',
    nombre: 'Interruptor Termomagnético Riel DIN 2P 63A 6kA Curva C (mMC6)',
    marca: 'Eaton',
    precio: 48.60,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético 2P 63A, curva C, poder de corte 6kA / 400V.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004128',
    modelo: 'mMCM-C10/2',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 2P 10A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 38.67,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor automático 2P 10A, capacidad de corte 10kA / 400V para aplicaciones industriales.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004132',
    modelo: 'mMCM-C32/2',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 2P 32A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 21.57,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor automático 2P 32A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4004134',
    modelo: 'mMCM-C50/2',
    nombre: 'Interruptor Termomagnético Industrial Riel DIN 2P 50A 10kA Curva C (mMCM)',
    marca: 'Eaton',
    precio: 76.34,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor automático 2P 50A, 10kA / 400V industrial.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005756',
    modelo: 'mMCT-C080/2',
    nombre: 'Interruptor Termomagnético de Gran Potencia Riel DIN 2P 80A 20kA Curva C (mMCT)',
    marca: 'Eaton',
    precio: 155.64,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético de alta potencia y gran poder de corte 2P 80A, 20kA / 400V para cabecera de tableros.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
  {
    codigoInterno: '4005758',
    modelo: 'mMCT-C125/2',
    nombre: 'Interruptor Termomagnético de Gran Potencia Riel DIN 2P 125A 20kA Curva C (mMCT)',
    marca: 'Eaton',
    precio: 156.32,
    unidad: 'PEN',
    categoria: 'Interruptores Termomagnéticos',
    subfamilia: 'Interruptores Termomagnéticos (ITM)',
    familia: 'Equipos Eléctricos',
    descripcion: 'Interruptor termomagnético de alta potencia 2P 125A, 20kA / 400V para riel DIN.',
    imagenUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=800',
  },
];

async function main() {
  console.log('🚀 Iniciando importación masiva de productos...');

  const todos = [
    ...DEHN_SENAL,
    ...ESAFE_TABLEROS_CAJAS,
    ...ESAFE_CINTILLOS,
    ...EATON_ITM,
  ];

  console.log(`📦 Total de ítems en este lote: ${todos.length}`);

  let procesados = 0;

  for (const prod of todos) {
    // 1. Familia
    let familia = await prisma.familia.findUnique({
      where: { nombre: prod.familia },
    });
    if (!familia) {
      familia = await prisma.familia.create({
        data: { nombre: prod.familia, descripcion: `Familia de ${prod.familia}` },
      });
    }

    // 2. Subfamilia
    let subfamilia = await prisma.subfamilia.findUnique({
      where: {
        familiaId_nombre: {
          familiaId: familia.id,
          nombre: prod.subfamilia,
        },
      },
    });
    if (!subfamilia) {
      subfamilia = await prisma.subfamilia.create({
        data: {
          nombre: prod.subfamilia,
          familiaId: familia.id,
        },
      });
    }

    // 3. Upsert de Equipo
    await prisma.equipo.upsert({
      where: { codigoInterno: prod.codigoInterno },
      update: {
        nombre: prod.nombre,
        modelo: prod.modelo,
        marca: prod.marca,
        precio: prod.precio,
        unidad: prod.unidad,
        tipo: TipoTransaccion.VENTA,
        estado: EstadoEquipo.DISPONIBLE,
        disponible: true,
        categoria: prod.categoria,
        descripcion: prod.descripcion,
        imagenUrl: prod.imagenUrl,
        ubicacion: 'Almacén Central',
        familiaId: familia.id,
        subfamiliaId: subfamilia.id,
      },
      create: {
        codigoInterno: prod.codigoInterno,
        nombre: prod.nombre,
        modelo: prod.modelo,
        marca: prod.marca,
        precio: prod.precio,
        unidad: prod.unidad,
        tipo: TipoTransaccion.VENTA,
        estado: EstadoEquipo.DISPONIBLE,
        disponible: true,
        categoria: prod.categoria,
        descripcion: prod.descripcion,
        imagenUrl: prod.imagenUrl,
        ubicacion: 'Almacén Central',
        familiaId: familia.id,
        subfamiliaId: subfamilia.id,
      },
    });

    procesados++;
    console.log(`  ✅ [${prod.codigoInterno}] ${prod.nombre} (${prod.unidad} ${prod.precio})`);
  }

  console.log(`\n🎉 Lote completado con éxito: ${procesados} productos registrados.`);
}

main()
  .catch((e) => {
    console.error('❌ Error en la importación masiva:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
